name:                3DAdventureIn2D
version:             0.1.0.0
github:              "githubuser/3DAdventureIn2D"
license:             BSD3
author:              "Johannes Ganser"
maintainer:          "ganser@uni-bremen.de"
copyright:           "2020 Johannes Ganser"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/3DAdventureIn2D#readme>

dependencies:
- base >= 4.7 && < 5
#- Yampa >= 0.11 && < 0.20
- hsnoise >= 0.0.2
- processing-for-haskell >= 0.1.0.1
- extra >= 1.6.18
#- xeno >= 0.3.4

library:
  source-dirs: src

executables:
  3DAdventureIn2D-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 3DAdventureIn2D

tests:
  3DAdventureIn2D-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 3DAdventureIn2D
